"""
Django settings for schat project.

Generated by 'django-admin startproject' using Django 3.2.9.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-9zvms(_l5sol&m!juze9^fq4b0nfp6!gjtntk$9@&i3byej^0-'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["testserver", 'localhost:8000', 'localhost', 'http://localhost:8000/simple_chatbot/']


# Application definition

INSTALLED_APPS = [
    'simple_chatbot',
    'schatapp.apps.SchatappConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'schat.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'schat.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'chatappdb',
        'USER' : 'aiva',
        'PASSWORD' : 'hoopproj1',
        'HOST' : 'localhost'
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kuala_Lumpur'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'schat/static')
]

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


SIMPLE_CHATBOT = {

    'responses': (
        ("schatapp.responses.GreetingResponse", "Greeting"),
        ("schatapp.responses.GoodbyeResponse", "Goodbye"),
        ("schatapp.responses.IncentiveResponse", "Incentive"),
        ("schatapp.responses.CredibleResponse", "Credible"),
        ("schatapp.responses.DataPrivacyResponse", "Data_Privacy"),
        ("schatapp.responses.TechQResponse", "Tech_Q"),
        ("schatapp.responses.ChatQResponse", "Chat_Q"),
        ("schatapp.responses.SocialQResponse", "Social_Q"),
        ("schatapp.responses.SmartMachineQResponse", "SmartMachine_Q"),
        ("schatapp.responses.FintechProductResponse", "FintechProduct_Q"),
        ("schatapp.responses.ReturnStrategyResponse", "Return_or_Strategy"),
        ("schatapp.responses.InterestCheckResponse", "Interest_Check"),
        ("schatapp.responses.LegalResponse", "Legal_Approval"),
        ("schatapp.responses.PositiveOneResponse", "PositiveOne"),
        ("schatapp.responses.NegativeOneResponse", "NegativeOne"),
        ("schatapp.responses.StartResponse", "How_Start"),
        ("schatapp.responses.Q1Response", "Q1"),
        ("schatapp.responses.Q1PositiveResponse", "Q1_Positive_R"),
        ("schatapp.responses.Q2PositiveResponse", "Q2_Positive_R"),
        ("schatapp.responses.Q3PositiveResponse", "Q3_Positive_R"),
        ("schatapp.responses.Q4PositiveResponse", "Q4_Positive_R"),
        ("schatapp.responses.Q5PositiveResponse", "Q5_Positive_R"),
        ("schatapp.responses.OthersResponse", "Others"),
    ),
}